In [5]:
##Basic String Operations
# 1.String Manipulation
#  Create the string variable
text = "Welcome to the world of Data Science!"
# Extract the word "Data"
extracted_word = text.split()[6]  # Extracting "Data"
#  Replace "Science" with "Analytics"
replaced_text = text.replace("Science", "Analytics")
#  Convert the entire string to uppercase
uppercase_text = text.upper()
#  Reverse the entire string
reversed_text = text[::-1]
# Output the results
print("Extracted Word:", extracted_word)
print("Replaced Text:", replaced_text)
print("Uppercase Text:", uppercase_text)
print("Reversed Text:", reversed_text)  # (with a regular space)

Extracted Word: Science!
Replaced Text: Welcome to the world of Data Analytics!
Uppercase Text: WELCOME TO THE WORLD OF DATA SCIENCE!
Reversed Text: !ecneicS ataD fo dlrow eht ot emocleW


In [6]:
# 2.String Methods
# Define the string
text = "Python programming is fun!"
# Count the number of occurrences of the letter 'm'
count_m = text.count('m')
# Find the index position of the word 'fun'
index_fun = text.index('fun')
# Check if the string starts with 'Python' and ends with an exclamation mark
starts_with_python = text.startswith('Python')
ends_with_exclamation = text.endswith('!')
# Output the results
print("Occurrences of 'm':", count_m)
print("Index position of 'fun':", index_fun)
print("Starts with 'Python':", starts_with_python)
print("Ends with '!':", ends_with_exclamation)

Occurrences of 'm': 2
Index position of 'fun': 22
Starts with 'Python': True
Ends with '!': True


In [7]:
##Formatting String
#1. String Formatting
#  Create the string template with placeholders
template = "My name is {name}, I am {age} years old, and I am a {profession}."

#  Populate the template with values
formatted_string = template.format(name="John", age=30, profession="Data Scientist")

# Output the result
print(formatted_string)

My name is John, I am 30 years old, and I am a Data Scientist.


In [8]:
##Formatting String
#2.StringLiterals(f-strings)
#  Define the variables
name = "John"
age = 30
profession = "Data Scientist"

# Create the formatted string using f-strings
formatted_string = f"My name is {name}, I am {age} years old, and I am a {profession}."

# Output the result
print(formatted_string)

My name is John, I am 30 years old, and I am a Data Scientist.


In [10]:
##:Understanding Pandas Data Structure
# 1. Series and Data Frames
import pandas as pd
# Create a Pandas Series from a list of integers
integer_list = [1, 2, 3, 4, 5]
series = pd.Series(integer_list)
#: Create a Pandas DataFrame with the specified data
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Profession": ["Engineer", "Data Scientist", "Teacher"]
}
dataframe = pd.DataFrame(data)
# Display the first and last row of the DataFrame
first_row = dataframe.iloc[0]
last_row = dataframe.iloc[-1]
# Select and display the 'Name' column
name_column = dataframe['Name']

#: Filter the DataFrame to show only rows where the 'Age' is greater than 28
filtered_df = dataframe[dataframe['Age'] > 28]

# Output the results
print("Pandas Series:")
print(series)

print("\nFirst Row:")
print(first_row)

print("\nLast Row:")
print(last_row)

print("\nName Column:")
print(name_column)

print("\nFiltered DataFrame (Age > 28):")
print(filtered_df)

Pandas Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

First Row:
Name             Alice
Age                 25
Profession    Engineer
Name: 0, dtype: object

Last Row:
Name          Charlie
Age                35
Profession    Teacher
Name: 2, dtype: object

Name Column:
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

Filtered DataFrame (Age > 28):
      Name  Age      Profession
1      Bob   30  Data Scientist
2  Charlie   35         Teacher


In [29]:
##experimenting with Pandas Functions
# Data Aggregation and Analysis
import pandas as pd

# Load the CSV file
spreadsheet = pd.read_csv('D:\\Aditya.csv')

# Check column names
print("Column Names:")
print(spreadsheet.columns)

# Calculate mean, median, and standard deviation of a numeric column
# Clean up column names (optional)
spreadsheet.columns = spreadsheet.columns.str.strip()  # Removes any leading/trailing spaces

# Replace 'Salary' with the actual name
mean_value = spreadsheet['Salary'].mean()  # Adjust this as needed
median_value = spreadsheet['Salary'].median()
std_dev_value = spreadsheet['Salary'].std()

print("\nMean of Salary:", mean_value)
print("Median of Salary:", median_value)
print("Standard Deviation of Salary:", std_dev_value)


Column Names:
Index(['Name', 'Age', 'Salary ', 'Department'], dtype='object')

Mean of Salary: 70000.0
Median of Salary: 70000.0
Standard Deviation of Salary: 15811.388300841896


In [28]:
## IntroductiontoNumPy
 #1. NumPyBasics
import numpy as np
# Create a 1D NumPy array with values from 1 to 10
array_1d = np.arange(1, 11)
print("1D Array (1 to 10):")
print(array_1d)
# Create a 2D NumPy array with shape (3, 3) containing random integers between 1 and 20
array_2d = np.random.randint(1, 21, size=(3, 3))
print("\n2D Array (3x3) with random integers between 1 and 20:")
print(array_2d)
#  Find the mean and standard deviation of the 2D array
mean_2d = np.mean(array_2d)
std_dev_2d = np.std(array_2d)
print("\nMean of the 2D Array:", mean_2d)
print("Standard Deviation of the 2D Array:", std_dev_2d)
#  Reshape the 2D array into a 1D array
reshaped_array_1d = array_2d.reshape(-1)
print("\nReshaped 1D Array from 2D Array:")
print(reshaped_array_1d)
#  Sort the 1D array in ascending order
sorted_array_1d = np.sort(reshaped_array_1d)
print("\nSorted 1D Array in Ascending Order:")
print(sorted_array_1d)


1D Array (1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

2D Array (3x3) with random integers between 1 and 20:
[[ 3 19  8]
 [ 6  6 16]
 [12 14 19]]

Mean of the 2D Array: 11.444444444444445
Standard Deviation of the 2D Array: 5.619630496178574

Reshaped 1D Array from 2D Array:
[ 3 19  8  6  6 16 12 14 19]

Sorted 1D Array in Ascending Order:
[ 3  6  6  8 12 14 16 19 19]
